# Dockerfile-nginx
FROM nginx:latest

# Remove default nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom configuration file from the current directory
COPY ./default.conf /etc/nginx/conf.d/default.conf