# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

# Servidor nginx
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx-battle-stalingrad
    container_name: nginx-battle-stalingrad-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  # Configuración de php-fpm
  php-fpm:
    build: 
      context: .
      dockerfile: Dockerfile-fpm
    image: php-fpm-battle-stalingrad
    container_name: php-fpm-battle-stalingrad-container
    volumes:
      - ./:/var/www/html
